#!/usr/bin/env bash
# This script configures the nginx server to have a custom 404 page that
# contains the string Ceci n'est pas une page.

sudo apt update
sudo apt install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/esty2022 permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart nginx after implementig changes

sudo service nginx restart
