#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy 

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo "
frontend abiolafashblog.tech
        bind *:80
	mode http
        default_backend abiolafash_backend

backend abiolafash_backend
        balance roundrobin
        server 220204-web-01 100.25.141.97:80 check
        server 220204-web-02 54.175.255.86:80 check
" >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy start
